### ISSUE TITLE
Add TCP support

### ISSUE THREAD

**Issue by Shatur95** [neovim/nvim-lsp#131]
Recently Godot 3.2 was released with LSP support. But LSP works only through Websocket. [This](https://github.com/godotengine/godot/pull/35864#) PR switches Godot's LSP to TCP and now can be suported for the Vim plugins. I tested it with coc.nvim and everything works. Does `nvim-lsp` will support TCP?

**Comment by h-michael** [comment]
Not planed yet. I didn't think there was a language server that didn't provide a way to use it on std io.

It may be misleading because the name of the plugin is not appropriate now, but this plugin is a collection of settings for using each language server from Nvim's built-in lsp.
The core logic of Nvim's lsp client is in Nvim itself. So please post an issue on lsp client at [neovim/neovim](https://github.com/neovim/neovim/issues/new/choose).

**Comment by kovasap** [comment]
Did you ever get this working @Shatur?

**Comment by mjlbach** [comment]
You can use netcat (see godot), otherwise there is still no TCP support. Echoing h-michael's comment, this is implemented in neovim core (lspconfig is just a list of configurations for neovim's built-in language server). The tracking issue for lsp support is here: https://github.com/neovim/neovim/issues/11911

**Comment by kovasap** [comment]
How would I set up a config to use netcat?  Is there an example language server config in this repo I can use as an example?

**Comment by mjlbach** [comment]
> You can use netcat (see godot)

**Comment by kovasap** [comment]
Ah my apologies, found https://github.com/neovim/nvim-lspconfig/blob/master/lua/lspconfig/gdscript.lua.  I thought you were referring to the godot documentation.  This works for me after updating to Godot 3.3.2!
