### ISSUE TITLE
Add statusline support

### ISSUE THREAD

**Issue by Shatur95** [neovim/nvim-lsp#133]
vim-lsp can show occurred errors at statusline ([issue](https://github.com/prabirshrestha/vim-lsp/issues/346), [PR](https://github.com/prabirshrestha/vim-lsp/issues/346)). Is it possible to implement it in this plugin too?

**Comment by h-michael** [comment]
It may be misleading because the name of the plugin is not appropriate now, but this plugin is a collection of settings for using each language server from Nvim's built-in lsp.
The core logic of Nvim's lsp client is in Nvim itself. So please post an issue on lsp client at [neovim/neovim](https://github.com/neovim/neovim/issues/new/choose).
