### ISSUE TITLE
vim.uri not found

### ISSUE THREAD

**Issue by mezeipetister** [neovim/nvim-lsp#167]
Hi Guys,

I have just downloaded nvim5.0 and started to install nvim-lsp via Plug but I got this error:

```shell
E5108: Error executing lua vim.lua:270: module 'vim.uri' not found:
```
Do you have any idea what can be wrong?

This is my init.vim

```
call plug#begin()
Plug 'neovim/nvim-lsp'
call plug#end()
```

**Comment by gavynriebau** [comment]
@mezeipetister I had the same problem after making a mistake when installing by manually copying files extracted from the `.tar.gz` release file.

You can confirm whether your issue is the same by running

```bash
$ ls /usr/share/nvim/runtime/lua/vim/
```

If the directory doesn't contain a `uri.lua` file you probably also made a mistake.
You can fix it by copying the files again, e.g.

```bash
$ cd /tmp
$ tar xvf nvim-linux64.tar.gz
$ cd /tmp/nvim-linux64
$ sudo cp -r share/* /usr/share/
```

If this doesn't work for you I'd suggest testing whether you still have the same problem when running from the `.appimage` file and providing more output from the `:messages` vim command.

**Comment by mezeipetister** [comment]
I uninstalled nvim, added the dev ppa and installed it via the dev ppa. Now I have nvim5.0-dev and it works well.

**Comment by h-michael** [comment]
@gavynriebau Thanks following up :)
