### ISSUE TITLE
Unable to get omnicompletion on type working in neovim.

### ISSUE THREAD

**Issue by yashLadha** [neovim/nvim-lsp#223]
My config:

```
lua << EOF
require'nvim_lsp'.dartls.setup{}
require'nvim_lsp'.tsserver.setup{}
require'nvim_lsp'.gopls.setup{}
require'nvim_lsp'.clangd.setup{}
EOF

autocmd Filetype javascript setlocal omnifunc=v:lua.vim.lsp.omnifunc
autocmd Filetype cpp setlocal omnifunc=v:lua.vim.lsp.omnifunc

nnoremap <silent> gd    <cmd>lua vim.lsp.buf.declaration()<CR>
nnoremap <silent> <c-]> <cmd>lua vim.lsp.buf.definition()<CR>
nnoremap <silent> K     <cmd>lua vim.lsp.buf.hover()<CR>
nnoremap <silent> gD    <cmd>lua vim.lsp.buf.implementation()<CR>
nnoremap <silent> <c-k> <cmd>lua vim.lsp.buf.signature_help()<CR>
nnoremap <silent> 1gD   <cmd>lua vim.lsp.buf.type_definition()<CR>
nnoremap <silent> gr    <cmd>lua vim.lsp.buf.references()<CR>
nnoremap <silent> g0    <cmd>lua vim.lsp.buf.document_symbol()<CR>

```

**Comment by h-michael** [comment]
@yashLadha Please report in the format of the issue template.




- `nvim --version`:
- nvim-lsp version(commit hash):
- `:checkhealth` result
- What language server(If the problem is related to a specific language server):
- Operating system/version:
- Terminal name/version:
- `$TERM`:

### How to reproduce the problem from neovim startup

### Actual behaviour

### Expected behaviour

**Comment by yashLadha** [comment]
Resolved through `InsertPre` hook 👍

**Comment by david0** [comment]
Maybe I faced the same issue.
omnicomplete was working for python, but not for cpp (clangd).
omnifunc was set to `v:lua.vim.lsp.omnifunc` when I checked after opening the cpp file.
this fixed it:
```
autocmd FileType cpp set omnifunc=v:lua.vim.lsp.omnifunc
```
