### ISSUE TITLE
PYLS opening preview window

### ISSUE THREAD

**Issue by nomasprime** [neovim/nvim-lsp#286]
- `nvim --version`: v0.5.0-21453e8f0
- nvim-lsp version(commit hash): a82ce0e
- What language server(If the problem is related to a specific language server): pyls 0.1.6
- Operating system/version: MacOS 15.15.5
- Terminal name/version: iTerm nightly
- `$TERM`: 256

### How to reproduce the problem from neovim startup

With pyls and either deoplete LSP or another completion library NeoVim's intent on opening a preview window but only with pyls AFAIK.

### Actual behaviour

Preview window with completion.

### Expected behaviour

Not opening unwanted preview windows.

**Comment by nomasprime** [comment]
Don't know why this wasn't happening with solargraph as well but this fix was `set completeopt-=preview`.

**Comment by ms-jpq** [comment]
To add to that, this has the annoying behaviour if you accidently close your main window, and your preview window is the only one left, it will cause issues.

Because then you will habitually try to switch buffer in the preview window, but then since it's still the preview window, when the preview inevitably updates, it will destory whatever work you have done.

This is not at all easy to figure out, and really seems like a bug.

**Comment by Shougo** [comment]
This is bug?  Really?
I don't think so.

**Comment by nomasprime** [comment]
Thought it might be a bug when I raised but, like I said, it seems to be intended behaviour and the above setting stops it happening.

Closing this issue, any improvements can be raised in a new issue.

**Comment by Shougo** [comment]
I think this is feature.  Other omnifunc sets preview window information.
And you can disable preview window feature by `completeopt`.
So no problem.
