### ISSUE TITLE
`set -o pipefail` fails in ubuntu

### ISSUE THREAD

**Issue by yangyangxcf** [neovim/nvim-lsp#39]
`sh` on Ubuntu points to `/bin/dash`, which has no `-o` option and fails all `LspInstall` commands.

**Comment by norcalli** [comment]
:( Of course, there are non-POSIX `sh` out there. The shell script requirement was a temporary measure anyway. I've been trying to clean up pure Lua solution, so instead of trying to go down the road of customizing for each distro, we'll probably just do that first (unless someone wants to contribute a solution).

**Comment by lithammer** [comment]
Just remove the `-o pipefail` option, there's no piping involved anyway as far as I can tell.

**Comment by norcalli** [comment]
@lithammer true. I just used my sane defaults, but we aren't piping. `-euf` is still available in dash.

**Comment by norcalli** [comment]
@yangyangxcf a fix for this was pushed (accidentally to master) which removed pipefail as an option. I would recommend updating.
