### ISSUE TITLE
rename "skeleton" to "configs"

### ISSUE THREAD

**Issue by justinmk** [neovim/nvim-lsp#64]
`nvim_lsp/skeleton.lua` is not really a skeleton, it's a `configs`  class that provides

1. actual functionality
2. a bunch of configs

Each config is added to the `configs` object (FKA "skeleton") as a property. Those configs are not "templates", they are "configs". So we should clean up the wording in various places to say "config" instead of "skeleton"/"template".

General guideline: avoid extra jargon when possible.

**Comment by norcalli** [comment]
To be fair it started as a skeleton that I was copy pasting and then I turned it into a config metaclass thing, if you were curious why the name exists. I just didn't rename the file since it was assume to be internal only, but then people wanted to use it with private servers, so it got slightly exposed.
